name: chat_vocab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  bottom_bar: ^2.0.5
  circular_countdown_timer: ^0.2.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  google_fonts: ^6.3.2
  image_picker: ^1.2.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  sizer: ^3.1.3
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
